### ISSUE TITLE
Podatki

### ISSUE THREAD

**Issue by jaanos** [KatjaB7/Knjiznica#2]
Vidim, da sta na svojem repozitoriju naredili vejo z imenom `Podatki`, in vanjo naložili podatke v obliki CSV. Z uporabo vej ni sicer nič narobe - tako lahko npr. delata na novih funkcionalnostih, ne da bi spreminjali osnovne aplikacije na veji `master` - a podatke vendarle potrebujeta za svojo aplikacijo, in sicer znotraj mape `podatki`.

Da naložene datoteke pridružita v osnovno aplikacijo, naredita tako:
1. V Visual Studio Code-u naredita pull (Ctrl+Shift+P, nato pa napišita `git pull` in pritisnita Enter).
2. Preklopita na vejo `Podatki`: Ctrl+Shift+P, `git checkout`, potem pa napišita `Podatki`.
3. Ustvarita mapo `podatki` (male črke, saj tako podajata v programu): v pogledu datotek klikneta na drugo ikono z leve (*New Folder*) in vpišeta ime mape.
4. Premaknita datoteke CSV v novo mapo (lahko jih kar potegneta vanjo).
5. Preimenujta datoteke tako, da se bodo imena ujemala s tistimi v kodi (ali pa popravita v kodi). V izogib morebitnim težavam svetujem, da se izogibata šumnikom v imenih datotek.
6. Naredita commit, ki vključuje narejene spremembe.
7. Preklopita na vejo `master`: Ctrl+Shift+P, `git checkout`, `master`.
8. Pridružita vejo `Podatki` Ctrl+Shift+P, `git merge`, `Podatki`.
9. Naredita push, da objavita spremembe na GitHubu.

Tako bosta imeli podatke na glavni veji na pravem mestu in bo program lahko deloval.

**Comment by KatjaB7** [comment]
Hvala za odgovor sem delala doma, kjer sem samo dodala da imam, ker doma nimam Visual studio code. Sem sedaj popravila. Hvala.

**Comment by jaanos** [comment]
V redu, bom zaprl issue. Seveda ga lahko tudi sami zapreta, ko razrešita zadevo, tako da klikneta na **Close issue** (ali **Close and comment**, če ob tem še kaj napišeta), ali pa tako, da v sporočilo ob commitu vključita *Close #2*, kjer je #2 številka issueja.
