### ISSUE TITLE
Regristracija, pomoč

### ISSUE THREAD

**Issue by KatjaB7** [KatjaB7/Knjiznica#3]
Pozdravljeni !

1.problem
Imava problem pri registraciji in prijavi. V  glavno stran, modele in spletni vmesnik sem dodala vse potrebno za prijavo tako kot smo naredili na predavanjih in tako kot je narejeno v filmih. Ampak ne dela sedaj mi te tpl strani kar zruši ko želim dodati knjigo/založbo. In ne vem zakaj.

2.problem
V tekstovnem vmesniku ko želiva podatke o članih nama jih ne izpiše. Je že delalo in je bilo prav in tudi koda se nama zdi pravilna. Ampak kar ne dela več pa sva že vse poizkusili zakaj ne.

3.problem
Enako pri avtorjih nama noče izpisati njihovih knjig če npr. v spletnem vmesniku iščeva Desa Muck pri iskanju avtorja, nama bo sesulo zadevo in nama ne izpiše vse knjige ki jih je ta pisateljica napisala.

Bi prosili za pomoč ker ne veva kje je problem, če je kaj manjšega ali se raje oglasiva na govorilno uro?

Hvala, Katja in Zala

**Comment by jaanos** [comment]
Najprej bi opozoril na probleme pri samem uvozu. Ker imata vajine podatke v datotekah s kodiranjem znakov *Windows-1250*, bo treba v `baza.py` pri vsakem ukazu `open` dodati še parameter `encoding='Windows-1250'`. Brez tega se bodo datoteke pravilno prebrale le, če je to kodiranje znakov privzeto na računalniku, kjer teče program (kar je večinoma res pri slovenskih Windowsih, drugod pa večinoma ne).

Prav tako pride do problema pri uvozu v tabelo `izposoja`. V `izposoja.csv` imata namreč podatke za stolpec `strosek`, a se ta stolpec v `baza.py` ne ustvari. Poskrbita torej, da bo tabela imela tudi ta stolpec. Opažam sicer, da se (zaenkrat?) nikjer ne uporablja - če ga ne bosta imeli, potem namesto tega odstranita te podatke iz `izposoja.csv` ter popravita ER diagram. Svetoval bi še, da poskrbita za ustrezen glavni ključ v tabeli `izposoja` - primerno ime bi seveda bilo `id`, trenutni stolpec s tem imenom pa raje preimenujta v npr. `knjiga`. Seveda bo potrebno potem uvoz prirediti tako, da pri `INSERT` v to tabelo eksplicitno podasta stolpce, kamor se vnašajo podatki.

Da vama bo delovala prijava, bosta potrebovali še tabelo `uporabniki`. Svetujem, da v `baza.py` kar skopirata njeno ustvarjanje iz vzorčnega projekta:

https://github.com/jaanos/najboljsi-filmi/blob/6696b20a89372d9dc3ed5d7b06776814018f3f9d/baza.py#L66-L72

Pri izpisu podatkov o članih je problem tukaj:

https://github.com/KatjaB7/Knjiznica/blob/64f1678d9b85e687503ff4ef974c2622127afd62/tekstovni_vmesnik.py#L83-L87

Funkcija `modeli.podatki_knjig` namreč vrača seznam četveric (in ne trojic, kot se tukaj pričakuje). Če torej dodasta še en podčrtaj, bo delovalo (naslov knjige je še vedno drugi element četverice).

Če v spletni vmesnik napišem *Desa Muck* pri iskanju po avotrju, mi jo najde, po kliku na povezavo pa pride do napake. Ta se pojavi pri izvajanju te poizvedbe:

https://github.com/KatjaB7/Knjiznica/blob/64f1678d9b85e687503ff4ef974c2622127afd62/modeli.py#L181-L184

Pri `execute` namreč podasta `id_avtorja` kot podatek, a v poizvedbi ni nobenega vprašaja, kamor bi se lahko vstavil. Dodati bo treba torej še pogoj, npr. `WHERE avtor = ?`.

**Comment by KatjaB7** [comment]
Hvala  sva popravili, edino ne veva tam sva spremenile id v knjiga nevema pa kako zdaj ta uvozi spremenit.
Pa sedaj imava pa nov problem pri tekstovnem vmesniku ko mama podatki o knjigi, da nama pri avtorji in založbi ne izpiše vredu. Če dama na koncu execute lastrowid nama napiše 0, če ne dama nič pa nama izpiše ime objekta.

**Comment by jaanos** [comment]
Svetujem, da v tabelo `izposoja` dodasta stolpec `id`, torej
```sql
        CREATE TABLE izposoja (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            knjiga          INTEGER REFERENCES knjiga(id),
            datum_izposoje  DATE,
            datum_vracila   DATE,
            rok_vracila     DATE,
            clan            INTEGER REFERENCES clan(id)
        );
```
Potem v funkciji `uvozi_izposoje` priredita stavek `INSERT` tako, da eksplicitno povesta, v katere stolpce naj se podatki vstavljajo:
```python
        poizvedba = """
            INSERT INTO izposoja ({}) VALUES ({})
        """.format(', '.join(stolpci),
                   ', '.join(["?"] * len(stolpci)))
```
Da bo to delovalo, se morajo imena stolpcev v podatkih ujemati z imeni stolpcev v tabeli - v `izposoja.csv` torej popravita ime zadnjega stolpca v `clan`.

`lastrowid` se uporablja pri dodajanju v bazo (stavek `INSERT`) in vrne ID dodane vrstice. V vajinem primeru gre za običajno poizvedbo - ker vesta, da bo rezultat natanko eden, lahko uporabita `fetchone` in izluščita vrednost iz rezultata:
```python
avtor, = cur.execute(poizvedba_za_avtorja, [id_knjige]).fetchone()
```
Podobno naredita še za založbo - pravzaprav ni razloga, da ne bi z eno poizvedbo pridobili tako avtorja kot založbe.

**Comment by KatjaB7** [comment]
Najlepša hvala za pomoč.
Ponovno sva naleteli na problem, upava da zadnjič. Sedaj imava problem pri izposoji v spletnem vmesniku, naredili sva seznam kjer izbereva člana in knjigo in ko želiva izvesti izposojo nama je nikoli ne doda ampak vedno izpiše "prišlo je do napake". 
Verjetno je problem nekje tukaj:
![slika](https://user-images.githubusercontent.com/37327204/53170309-1d2dd480-35e0-11e9-9fe5-55bb637cd6a7.png)

**Comment by jaanos** [comment]
`request.forms.getall` vrne seznam vseh vrednosti za podano spremenljivko, medtem ko funkcija `modeli.dodaj_izposojo` pričakuje posamezna ID-ja člana in knjige. Glede na to, da imata tako pri članu in knjigi možnost večkratne izbire, je seveda smiselno, da dobita vse vrednosti - bi pa morali funkcijo `modeli.dodaj_izposojo` potem klicati za vsak par izbranih vrednosti v dvojni zanki `for`.

Smiselno se mi sicer zdi, da lahko izbereta več knjig, medtem ko bi pričakoval, da lahko izbereta samo enega člana (ne zdi se mi ravno realistično, da bi si več ljudi hkrati izposodilo iste knjige). V tem primeru bi lahko do njegovega ID-ja dostopali kar z `request.forms.id_clan`, po uspešnem vnosu pa bi bilo smiselno preusmeriti na stran člana (in ne knjige, saj je teh lahko več).

**Comment by KatjaB7** [comment]
Najlepša hvala za vso pomoč, nama je uspelo.
